# how to configure the behavior tree navigator
# https://docs.nav2.org/configuration/packages/configuring-bt-navigator.html
bt_navigator:
  ros__parameters:
    use_sim_time: True
    global_frame: map # Reference frame for the global costmap
    robot_base_frame: body_link # Reference frame for the robot
    odom_topic: /odometry/filtered # Topic for the odometry
    bt_loop_duration: 10 # Duration (in milliseconds) for each iteration of BT execution
    default_server_timeout: 20 # Default timeout (in seconds) for action servers
    default_nav_to_pose_bt_xml: "/home/asimovo/assets/navigation_rosbot-1.0.0/path_planner_server/config/behavior.xml" # Full path to the behavior tree xml file to use for navigate to pose
    plugin_lib_names: # List of behavior tree node shared libraries
    - nav2_compute_path_to_pose_action_bt_node
    - nav2_compute_path_through_poses_action_bt_node
    - nav2_follow_path_action_bt_node
    - nav2_back_up_action_bt_node
    - nav2_spin_action_bt_node
    - nav2_wait_action_bt_node
    - nav2_clear_costmap_service_bt_node
    - nav2_is_stuck_condition_bt_node
    - nav2_goal_reached_condition_bt_node
    - nav2_goal_updated_condition_bt_node
    - nav2_initial_pose_received_condition_bt_node
    - nav2_reinitialize_global_localization_service_bt_node
    - nav2_rate_controller_bt_node
    - nav2_distance_controller_bt_node
    - nav2_speed_controller_bt_node
    - nav2_truncate_path_action_bt_node
    - nav2_goal_updater_node_bt_node
    - nav2_recovery_node_bt_node
    - nav2_pipeline_sequence_bt_node
    - nav2_round_robin_node_bt_node
    - nav2_transform_available_condition_bt_node
    - nav2_time_expired_condition_bt_node
    - nav2_distance_traveled_condition_bt_node
    - nav2_single_trigger_bt_node
    - nav2_is_battery_low_condition_bt_node
    - nav2_navigate_through_poses_action_bt_node
    - nav2_navigate_to_pose_action_bt_node
    - nav2_remove_passed_goals_action_bt_node
