# how to configure recoveries server
# https://docs.nav2.org/configuration/packages/configuring-behavior-server.html
recoveries_server: # node name
  ros__parameters:
    costmap_topic: local_costmap/costmap_raw # Raw costmap topic for collision checking
    footprint_topic: local_costmap/published_footprint # Topic for the footprint of the robot
    cycle_frequency: 10.0 # Frequency in Hz at which the recoveries are expected to run
    # recovery_plugins: ["spin", "backup", "wait"] # List of mapped plugin and below its parameters
    behavior_plugins: ["spin", "backup", "wait"] # List of mapped plugin and below its parameters
    spin:
      plugin: "nav2_behaviors/Spin"
    backup:
      plugin: "nav2_behaviors/BackUp"
    wait:
      plugin: "nav2_behaviors/Wait"
    global_frame: odom # Reference frame for the global costmap
    robot_base_frame: body_link # Reference frame for the robot
    transform_timeout: 0.1 # Time in seconds to wait for a transform to be available
    use_sim_time: true
    simulate_ahead_time: 2.0 # Time in seconds to simulate ahead of the current time
    max_rotational_vel: 1.0 # Maximum rotational velocity in rad/s
    min_rotational_vel: 0.4 # Minimum rotational velocity in rad/s
    rotational_acc_lim: 3.2 # Rotational acceleration limit in rad/s^2
